# Generated by Django 5.2.8 on 2025-11-15 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='busstop',
            name='bus_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsource_app.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='WaitLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('wait_duration', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('route', models.CharField()),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsource_app.busstop', verbose_name='Bus Stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
