# Generated by Django 5.2.8 on 2025-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource_app', '0002_busstop_average_rating_busstop_bus_photo_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='average_rating',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
