# Generated by Django 5.2.8 on 2025-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource_app', '0003_alter_busstop_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlogmodel',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='waitlogmodel',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
